### ISSUE TITLE
Error syncing

### ISSUE THREAD

**Issue by dentonjacobs** [bachya/ExpandSync#5]
I have been using aText for some time, but just downloaded Text Expander Touch. I set up Dropbox sync, cleared the sample data out of TextExpander, exported the aText data to CSV and ran the program, but got an error:

```
uninitialized constant ExpandSync::TextExpander::FileUtils
```

Any ideas on what I did wrong?

**Comment by bachya** [comment]
Sorry you're experiencing trouble; can you tell me what version of Ruby you're using?

**Comment by dentonjacobs** [comment]
Ruby version 2.0.0. I see now that you say this is for 1.9.3. I'll have to see if I can go about setting up a virtual environment for 1.9.3 and get this going. Thanks for your help!

**Comment by bachya** [comment]
It should be good to go for 1.9.3 and above. I'll check it out!

**Comment by dentonjacobs** [comment]
Thanks, let me know if I can provide any other information. My situation may be strange as I was loading TextExpander Touch for the first time ever. Regardless, whatever I can do to help, I'm happy to do.

**Comment by bachya** [comment]
Just added a new version; you can get it by running:

```
$ gem update expandsync
```

Let me know if it solves your problem; I'll keep this issue open for a day or so, just in case.

**Comment by dentonjacobs** [comment]
Perfect. That worked. Thanks!

**Comment by bachya** [comment]
Great to hear!
