### ISSUE TITLE
Invalid TextExpander XML file

### ISSUE THREAD

**Issue by ipante** [bachya/ExpandSync#6]
Hi!

Expandsync looks unable to recognize the TextExpander XML file. Here's the terminal output:

Invalid TextExpander XML file:
/var/root/Dropbox/TextExpander/Settings.textexpander

Any idea to fix that issue?

Many thanks for your help!

**Comment by ethan9482** [comment]
Hi, 

I am having the same issue. I think its because text expander changed the file extension for their settings from something else. Unfortunately I can't write code in any way shape or form to try and fix it. Hopefully the original author could take a look at it.

**Comment by ipante** [comment]
Hi,

Thanks for answering!
